const ALLOWED_MEDIA_HOSTS = [
  'cdn.discordapp.com',
  'media.discordapp.net',
  'images-ext-1.discordapp.net',
  'images-ext-2.discordapp.net',
  'discord.com'
];

function isAllowedInlineImage(raw) {
  const value = String(raw || '');
  // Generated by the content script from already-rendered Discord sticker SVGs.
  // Keep a conservative size cap so the download/fetch bridge cannot be abused
  // as a generic data-URL transport.
  return value.length <= 4 * 1024 * 1024 && /^data:image\/(?:svg\+xml|png|apng|gif|webp|jpeg);base64,[a-z0-9+/=]+$/i.test(value);
}

function isAllowedMediaUrl(raw) {
  if (isAllowedInlineImage(raw)) return true;
  try {
    const url = new URL(raw);
    if (url.protocol !== 'https:') return false;
    if (!ALLOWED_MEDIA_HOSTS.some(host => url.hostname === host || url.hostname.endsWith(`.${host}`))) return false;
    if (url.hostname === 'discord.com' &&
        !/\/stickers\/\d+/i.test(url.pathname) &&
        !/\/assets\/[^/?]+\.(?:avif|gif|jpe?g|png|svg|webp)$/i.test(url.pathname)) {
      return false;
    }
    return true;
  } catch (_) {
    return false;
  }
}

function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  const chunk = 0x8000;
  let binary = '';
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, Math.min(i + chunk, bytes.length)));
  }
  return btoa(binary);
}

const MEDIA_CHUNK_BYTES = 6 * 1024 * 1024; // 6 MiB; divisible by 3 for safe base64 concatenation.
const MEDIA_SESSION_TTL_MS = 5 * 60 * 1000;
const mediaFetchSessions = new Map();

function cleanupMediaFetchSessions() {
  const cutoff = Date.now() - MEDIA_SESSION_TTL_MS;
  for (const [token, session] of mediaFetchSessions) {
    if ((session.lastAccess || session.createdAt || 0) < cutoff) mediaFetchSessions.delete(token);
  }
}

async function fetchMedia(url) {
  if (!isAllowedMediaUrl(url)) throw new Error('Blocked non-Discord media URL.');
  const response = await fetch(url, { credentials: 'omit', redirect: 'follow' });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  const buffer = await response.arrayBuffer();
  return {
    ok: true,
    contentType: response.headers.get('content-type') || 'application/octet-stream',
    byteLength: buffer.byteLength,
    base64: arrayBufferToBase64(buffer)
  };
}

async function startMediaFetch(url) {
  if (!isAllowedMediaUrl(url)) throw new Error('Blocked non-Discord media URL.');
  cleanupMediaFetchSessions();
  const response = await fetch(url, { credentials: 'omit', redirect: 'follow' });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  const buffer = await response.arrayBuffer();
  const token = crypto.randomUUID();
  const now = Date.now();
  mediaFetchSessions.set(token, {
    buffer,
    contentType: response.headers.get('content-type') || 'application/octet-stream',
    createdAt: now,
    lastAccess: now
  });
  return {
    ok: true,
    token,
    contentType: response.headers.get('content-type') || 'application/octet-stream',
    byteLength: buffer.byteLength,
    chunkSize: MEDIA_CHUNK_BYTES,
    chunkCount: Math.ceil(buffer.byteLength / MEDIA_CHUNK_BYTES)
  };
}

function fetchMediaChunk(token, index) {
  cleanupMediaFetchSessions();
  const session = mediaFetchSessions.get(String(token || ''));
  if (!session) throw new Error('Media fetch session expired.');
  const i = Number(index);
  if (!Number.isInteger(i) || i < 0) throw new Error('Invalid media chunk index.');
  const start = i * MEDIA_CHUNK_BYTES;
  if (start >= session.buffer.byteLength) throw new Error('Media chunk index is out of range.');
  const end = Math.min(start + MEDIA_CHUNK_BYTES, session.buffer.byteLength);
  session.lastAccess = Date.now();
  return {
    ok: true,
    index: i,
    byteLength: end - start,
    base64: arrayBufferToBase64(session.buffer.slice(start, end))
  };
}

function endMediaFetch(token) {
  mediaFetchSessions.delete(String(token || ''));
  return { ok: true };
}

async function downloadUrl(url, filename) {
  if (!isAllowedMediaUrl(url)) throw new Error('Blocked non-Discord media URL.');
  const id = await chrome.downloads.download({
    url,
    filename,
    saveAs: false,
    conflictAction: 'overwrite'
  });
  return { ok: true, downloadId: id };
}


async function captureVisible(sender) {
  const windowId = sender?.tab?.windowId;
  if (typeof windowId !== 'number') throw new Error('Could not identify the Discord window.');
  if (!sender.tab.active) throw new Error('Discord must be the active tab for rendered-media capture.');
  const dataUrl = await chrome.tabs.captureVisibleTab(windowId, { format: 'png' });
  if (!dataUrl || !/^data:image\/png;base64,/i.test(dataUrl)) throw new Error('Visible-tab capture failed.');
  return { ok: true, dataUrl };
}

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message?.type === 'DHE_CAPTURE_VISIBLE') {
    captureVisible(sender)
      .then(sendResponse)
      .catch(err => sendResponse({ ok: false, error: err.message }));
    return true;
  }

  if (message?.type === 'DHE_FETCH_MEDIA_START') {
    startMediaFetch(message.url)
      .then(sendResponse)
      .catch(err => sendResponse({ ok: false, error: err.message }));
    return true;
  }

  if (message?.type === 'DHE_FETCH_MEDIA_CHUNK') {
    try { sendResponse(fetchMediaChunk(message.token, message.index)); }
    catch (err) { sendResponse({ ok: false, error: err.message }); }
    return false;
  }

  if (message?.type === 'DHE_FETCH_MEDIA_END') {
    try { sendResponse(endMediaFetch(message.token)); }
    catch (err) { sendResponse({ ok: false, error: err.message }); }
    return false;
  }

  if (message?.type === 'DHE_FETCH_MEDIA') {
    // Kept for backward compatibility with already-loaded older content scripts.
    fetchMedia(message.url)
      .then(sendResponse)
      .catch(err => sendResponse({ ok: false, error: err.message }));
    return true;
  }

  if (message?.type === 'DHE_DOWNLOAD_URL') {
    downloadUrl(message.url, message.filename)
      .then(sendResponse)
      .catch(err => sendResponse({ ok: false, error: err.message }));
    return true;
  }
});
